# Generated by Django 5.1.1 on 2025-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_review_comment_review_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
