# Generated by Django 5.1.1 on 2025-07-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deletion_pending',
            field=models.BooleanField(default=False),
        ),
    ]
