# Generated by Django 5.1.1 on 2025-07-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_profile_deletion_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('COD', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card')], default='COD', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('COD', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card')], default='Pending', max_length=20),
        ),
    ]
