# Generated by Django 5.1.1 on 2025-07-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('COD', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card'), ('Processing', 'Processing')], default='COD', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('COD', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card'), ('Processing', 'Processing')], default='Pending', max_length=20),
        ),
    ]
