# Generated by Django 5.1.1 on 2025-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card')], default='COD', max_length=10),
        ),
    ]
